const types = {
  SET_LOGIN: "SET_LOGIN",
  SET_LOGOUT: "SET_LOGOUT",
  SET_REPOSITORIES: "SET_REPOSITORIES",
  // UI
  SET_SIGN_UP_ERROR: "SET_SIGN_UP_ERROR",
  SET_LOGIN_ERROR: "SET_LOGIN_ERROR",
};

export default types;
